### ISSUE TITLE
a

### ISSUE THREAD

**Issue by plajos1** [salylgw/gammath_spot#5]

**Comment by salylgw** [comment]
Hi,

I just saw this email. I don't see this issue. Can you send me some more
detail on this?

Best regards,
Salyl

**Comment by salylgw** [comment]
Ah, I see this is marked as resolved. Was there any issue that I needed to
be aware of?

Best regards,
Salyl

**Comment by plajos1** [comment]
Hi,

I have started an issue, concerning the new version's behavior. When I have
realized how can I solve the problem, I have already started the issue on
Github. Unfortunately I was not able to delete it completely, so just
removed all the texts and left the "5".

The problem is that the:

   1. If you want to use the CLI and installed this software then run:
gammath_scraper
   sample_watchlist.csv > log_scraper.txt. See sample_watchlist.csv
   <https://github.com/salylgw/gammath_spot/blob/main/gammath_spot/sample_watchlist.csv>.
   If not installed but just obtained the source code then go to the directory
   gammath_spot/gammath_spot where all the source files are and run: python
   gammath_stocks_data_scraper.py sample_watchlist.csv > log_scraper.txt.

method is no longer working on my laptop. Earlier I was using the software
this way. (it was with the 9.5 version) The lines above was working since
the beginning.

As I have also installed the program I tried the

gammath_scorer sample_watchlist.csv > log_scorer.txt

method and it worked fine. So I have modified the batch file I am using to
this method. It seemed to me that the 9.5 was running really smoothly with
a quite large watchlist (1000 pcs. with 888 getting gscores)

I am about to install the 10.0 and see the result

br.: Louis

LOUIS PALANKI

skype:louis.palanki
+36-30-9418-367



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by salylgw** [comment]
Hi Louis,

Most of the changes I've made from the last couple of weeks are related to
supporting GUI as there are people requesting it. However, I tested both
CLI and GUI for all the versions from 9.x to 10.0 and CLI worked the same
as before. In fact I even ran it on MAC, Windows and Docker and it all
seems to be fine. Github is showing 0 issues open so I didn't see this when
I was actively making changes so didn't realize there was an issue until I
saw your email.

In any case, I have tested CLI and GUI versions with and without
installation and I don't see this issue. The way to pass the watchlist to
the program is still the same to all the main programs so I'm puzzled by
what you are seeing unless you have some local changes or missing watchlist
file. Please note that when someone installs the software, they won't have
the sample watchlist.csv unless they get it from the git repository or
create a new one (this is perhaps what it looks like based on the error
you are showing).

Watchlist size is not a limitation on CLI. If you are still seeing some
issue with v10.0, please let me know the detail like the log file, version
installed or cloned, if it is a problem only for a specific tool (e.g.
scraper, scorer, projector etc,) or for all tools etc. and I'll be happy to
check it out.

This week, I'll be caught up in some non-engineering issues but should be
able to allocate time for coding starting Tuesday.

Thanks,
Salyl

**Comment by plajos1** [comment]
Hi,

I have tested the 10.0 version today morning. I worked OK.

The 9.5 version wrote this kind of messages into the log:

Error while getting ticker price history for CRWD
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.

Error while getting ticker price history for RBLX
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.
WARNING: No decryption keys could be extracted from JS file. Falling back
to backup decrypt methods.

Br.: Louis

skype:louis.palanki
+36-30-9418-367


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by salylgw** [comment]
Hi Louis,

I think what you are seeing is a problem related to yfinance/Yahoo Finance.
If you see the PyPI page for yfinance, it is documented. He does update the
versions every now and then so the message you see can be specific to the
yfinance version you use.

I haven't fixed a version in my release and tend to pick the latest because
I know it is changing. In fact in recent times, lot of fundamentals data,
analysts info, short ratio etc. aren't working. I'm curious to know if
those work for you.

Best regards,
Salyl

**Comment by plajos1** [comment]
Hi,

You might be right: finance has to be renewed time-to-time. The error
message was clear that obtaining the data causes the problem, but I have
not realized that gammath uses finance.

br.: Louis

skype:louis.palanki
+36-30-9418-367
